version: '3.8'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  vue-app:
    build:
      context: ./front-end/transfers-front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
